# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/n880e/setup-makefiles.sh


PRODUCT_COPY_FILES += \
    vendor/zte/n880e/proprietary/bin/bluetoothd:system/bin/bluetoothd \
    vendor/zte/n880e/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/zte/n880e/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/zte/n880e/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/zte/n880e/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/zte/n880e/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/n880e/proprietary/bin/rild:system/bin/rild \
    vendor/zte/n880e/proprietary/bin/akmd8962_new:system/bin/akmd8962_new \
    vendor/zte/n880e/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/zte/n880e/proprietary/bin/wpa_cli:system/bin/wpa_cli \
    vendor/zte/n880e/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/zte/n880e/proprietary/bin/cat:system/bin/cat \
    vendor/zte/n880e/proprietary/bin/chmod:system/bin/chmod \
    vendor/zte/n880e/proprietary/bin/chown:system/bin/chown \
    vendor/zte/n880e/proprietary/bin/cmp:system/bin/cmp \
    vendor/zte/n880e/proprietary/bin/date:system/bin/date \
    vendor/zte/n880e/proprietary/bin/dd:system/bin/dd \
    vendor/zte/n880e/proprietary/bin/df:system/bin/df \
    vendor/zte/n880e/proprietary/bin/copypartnerapp:system/bin/copypartnerapp \
    vendor/zte/n880e/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/zte/n880e/proprietary/bin/dmesg:system/bin/dmesg \
    vendor/zte/n880e/proprietary/bin/getevent:system/bin/getevent \
    vendor/zte/n880e/proprietary/bin/getprop:system/bin/getprop \
    vendor/zte/n880e/proprietary/bin/hd:system/bin/hd \
    vendor/zte/n880e/proprietary/bin/hibernate:system/bin/hibernate \
    vendor/zte/n880e/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/zte/n880e/proprietary/bin/hostapd_cli:system/bin/hostapd_cli \
    vendor/zte/n880e/proprietary/bin/id:system/bin/id \
    vendor/zte/n880e/proprietary/bin/ifconfig:system/bin/ifconfig \
    vendor/zte/n880e/proprietary/bin/iftop:system/bin/iftop \
    vendor/zte/n880e/proprietary/bin/insmod:system/bin/insmod \
    vendor/zte/n880e/proprietary/bin/ioctl:system/bin/ioctl \
    vendor/zte/n880e/proprietary/bin/ionice:system/bin/ionice \
    vendor/zte/n880e/proprietary/bin/kill:system/bin/kill \
    vendor/zte/n880e/proprietary/bin/ln:system/bin/ln \
    vendor/zte/n880e/proprietary/bin/log:system/bin/log \
    vendor/zte/n880e/proprietary/bin/ls:system/bin/ls \
    vendor/zte/n880e/proprietary/bin/lsmod:system/bin/lsmod \
    vendor/zte/n880e/proprietary/bin/lsof:system/bin/lsof \
    vendor/zte/n880e/proprietary/bin/md5:system/bin/md5 \
    vendor/zte/n880e/proprietary/bin/mkdir:system/bin/mkdir \
    vendor/zte/n880e/proprietary/bin/mount:system/bin/mount \
    vendor/zte/n880e/proprietary/bin/logwrapper:system/bin/logwrapper \
    vendor/zte/n880e/proprietary/bin/usbchangemode:system/bin/usbchangemode \
    vendor/zte/n880e/proprietary/bin/usbconfig:system/bin/usbconfig \
    vendor/zte/n880e/proprietary/bin/mv:system/bin/mv \
    vendor/zte/n880e/proprietary/bin/nandread:system/bin/nandread \
    vendor/zte/n880e/proprietary/bin/netstat:system/bin/netstat \
    vendor/zte/n880e/proprietary/bin/newfs_msdos:system/bin/newfs_msdos \
    vendor/zte/n880e/proprietary/bin/notify:system/bin/notify \
    vendor/zte/n880e/proprietary/bin/printenv:system/bin/printenv  \
    vendor/zte/n880e/proprietary/bin/ps:system/bin/ps \
    vendor/zte/n880e/proprietary/bin/r:system/bin/r \
    vendor/zte/n880e/proprietary/bin/reboot:system/bin/reboot \
    vendor/zte/n880e/proprietary/bin/renice:system/bin/renice \
    vendor/zte/n880e/proprietary/bin/rm:system/bin/rm \
    vendor/zte/n880e/proprietary/bin/rmdir:system/bin/rmdir \
    vendor/zte/n880e/proprietary/bin/rmmod:system/bin/rmmod \
    vendor/zte/n880e/proprietary/bin/rmt_storage_recovery:system/bin/rmt_storage_recovery \
    vendor/zte/n880e/proprietary/bin/route:system/bin/route \
    vendor/zte/n880e/proprietary/bin/schedtop:system/bin/schedtop \
    vendor/zte/n880e/proprietary/bin/sendevent:system/bin/sendevent \
    vendor/zte/n880e/proprietary/bin/setconsole:system/bin/setconsole \
    vendor/zte/n880e/proprietary/bin/setprop:system/bin/setprop \
    vendor/zte/n880e/proprietary/bin/sh:system/bin/sh \
    vendor/zte/n880e/proprietary/bin/sleep:system/bin/sleep \
    vendor/zte/n880e/proprietary/bin/smd:system/bin/smd \
    vendor/zte/n880e/proprietary/bin/start:system/bin/start \
    vendor/zte/n880e/proprietary/bin/stop:system/bin/stop \
    vendor/zte/n880e/proprietary/bin/sync:system/bin/sync \
    vendor/zte/n880e/proprietary/bin/top:system/bin/top \
    vendor/zte/n880e/proprietary/bin/touch:system/bin/touch \
    vendor/zte/n880e/proprietary/bin/umount:system/bin/umount \
    vendor/zte/n880e/proprietary/bin/uptime:system/bin/uptime \
    vendor/zte/n880e/proprietary/bin/vmstat:system/bin/vmstat \
    vendor/zte/n880e/proprietary/bin/watchprops:system/bin/watchprops \
    vendor/zte/n880e/proprietary/bin/wipe:system/bin/wipe \
    vendor/zte/n880e/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/zte/n880e/proprietary/lib/libkpencore.so:system/lib/libkpencore.so \
    vendor/zte/n880e/proprietary/lib/libmedia_jni.so:system/lib/libmedia_jni.so \
    vendor/zte/n880e/proprietary/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
    vendor/zte/n880e/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/n880e/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/zte/n880e/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/zte/n880e/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/zte/n880e/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/n880e/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/n880e/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/zte/n880e/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/zte/n880e/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/zte/n880e/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/zte/n880e/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/zte/n880e/proprietary/lib/librabjni.so:system/lib/librabjni.so \
    vendor/zte/n880e/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/zte/n880e/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/zte/n880e/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/n880e/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/zte/n880e/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/n880e/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/zte/n880e/proprietary/lib/libSimCardAuth.so:system/lib/libSimCardAuth.so \
    vendor/zte/n880e/proprietary/lib/libstdc++.so:system/lib/libstdc++.so \
    vendor/zte/n880e/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
    vendor/zte/n880e/proprietary/lib/libutils.so:system/lib/libutils.so \
    vendor/zte/n880e/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/zte/n880e/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/n880e/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/zte/n880e/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/zte/n880e/proprietary/lib/hw/audio.primary.msm7627a.so:system/lib/hw/audio.primary.msm7627a.so \
    vendor/zte/n880e/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/zte/n880e/proprietary/lib/hw/audio_policy.msm7627a.so:system/lib/hw/audio_policy.msm7627a.so \
    vendor/zte/n880e/proprietary/lib/hw/copybit.msm7627a.so:system/lib/hw/copybit.msm7627a.so \
    vendor/zte/n880e/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
    vendor/zte/n880e/proprietary/lib/hw/gps.msm7627a.so:system/lib/hw/gps.msm7627a.so \
    vendor/zte/n880e/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/zte/n880e/proprietary/lib/hw/gralloc.msm7627a.so:system/lib/hw/gralloc.msm7627a.so \
    vendor/zte/n880e/proprietary/lib/hw/hwcomposer.msm7627a.so:system/lib/hw/hwcomposer.msm7627a.so \
    vendor/zte/n880e/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/zte/n880e/proprietary/lib/hw/lights.msm7627a.so:system/lib/hw/lights.msm7627a.so \
    vendor/zte/n880e/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/zte/n880e/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/zte/n880e/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \
    vendor/zte/n880e/proprietary/lib/drm/libfwdlockengine.so:system/lib/drm/libfwdlockengine.so \
    vendor/zte/n880e/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/zte/n880e/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/zte/n880e/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/zte/n880e/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/zte/n880e/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/zte/n880e/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/zte/n880e/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/zte/n880e/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/n880e/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/n880e/proprietary/wifi/fw_bcmdhd.bin:system/wifi/fw_bcmdhd.bin \
    vendor/zte/n880e/proprietary/wifi/fw_bcmdhd_apsta.bin:system/wifi/fw_bcmdhd_apsta.bin \
    vendor/zte/n880e/proprietary/wifi/fw_bcmdhd_p2p.bin:system/wifi/fw_bcmdhd_p2p.bin
    








